Feature/progress bar
FlockOfBirds/progress-bar pull request #1
Opened 2017-01-24 15:05 UTC by edwinmp

Release 0.1.0

2017-01-27 13:03 UTC, Andries-Smit reviewed
please update

2017-01-27 13:03 UTC, Andries-Smit commented on Gruntfile.js
> +    grunt.registerTask("default", [ "clean build", "watch" ]);
Please add `grunt-check-dependencies` like [https://github.com/akileng56/Range-slider/blob/master/Gruntfile.js](https://github.com/akileng56/Range-slider/blob/master/Gruntfile.js)

2017-01-27 13:03 UTC, Andries-Smit commented on README.md
> +* Render different bar types that is; default, striped and animated
Rephrase? 

> Render bar types; plane, striped or animated strips.

2017-01-27 13:03 UTC, Andries-Smit commented on README.md
> +* Show different bar colors that is; success, info, warning, danger
Rephrase?
> Bar colours; success, info, warning or danger

2017-01-27 13:03 UTC, Andries-Smit commented on README.md
> +
3 newline and the end, should 1

2017-01-27 13:03 UTC, Andries-Smit commented on karma.conf.js
> +};
Missing newline

2017-01-27 13:03 UTC, Andries-Smit commented on package.json
> +  "description": "Progress bar used to show percentage of progress for values 0 to 100",
`for values 0 to 100` is not true anymore. So it could be removed.

2017-01-27 13:03 UTC, Andries-Smit commented on package.json
> +    "url": ""
Missing URL

2017-01-27 13:03 UTC, Andries-Smit commented on package.json
> +    "url": ""
missing URL

2017-01-27 13:03 UTC, Andries-Smit commented on package.json
> +  "devDependencies": {
Please update (dev)dependecies with `> npm-check`

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +                        "red-progressbar-text": maximumValue < 1,
It not good to explicit name colours in styles. Better use `alert-progressbar-text`

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +    private executeMicroflow (action: string | undefined, guid: string | undefined) {
Suggestion API of progress circle also support open page.

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +            maximumValue = maximumValueAttribute ? Number(contextObject.get(maximumValueAttribute)) : maximumValue;
use `as number`

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +            bootstrapStyle = contextObject.get(bootstrapStyleAttribute || "") as BootstrapStyle || bootstrapStyle;
dont get attribute "". `contextObject.get(bootstrapStyleAttribute || "")`

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +            [ this.progressAttribute, this.bootstrapStyleAttribute, this.maximumValueAttribute ].forEach((attribute) =>
👍 like it!

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +dojoDeclare("com.mendix.widget.ProgressBar.ProgressBar", [ WidgetBase ], function (Source: any) {
no need for a space between `function (Source: any)`

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.xml
> +                <attributeType name="Integer" />
Missing types `long` and `decimal`

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.xml
> +                <attributeType name="Integer" />
Missing types `long` and `decimal`

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.xml
> +                <enumerationValue key="default">Default</enumerationValue>
`Default` does not represent the real rendering. `Plain` is maybe better, open to suggestions.

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.xml
> +                <enumerationValue key="default">Default (None)</enumerationValue>
`Default (None)` => `None`

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/Alert.ts
> +
missing newline

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +                        ? maximumValue < 1 ? "Invalid" : `${this.calculatePercentage(progress, maximumValue)}%`
nested ternary operators are hard to read;
Add () around inner statement 
Or use if statements

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +            window.console.warn("The maximum value is less than one. Progress is set to Invalid");
console error should not be used. UI messages should be shown to the user directly via an alert

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +            this.state.alertMessage ? createElement(Alert, { message: this.state.alertMessage }) : null
Can we move the statement to the component?

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/__tests__/ProgressBar.spec.ts
> +        expect(wrapper.childAt(0).text()).toEqual(`${300}%`);
split into 3 different tests

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/__tests__/ProgressBar.spec.ts
> +    it("should not have the class widget-progressbar-text-contrast when progress exceeds the threshold", () => {
add opposite test too.

2017-01-27 13:03 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ui/ProgressBar.css
> +.widget-progressbar-text-contrast.red-progressbar-text .progress-bar {
don't use colour names in classes, use functional names

2017-01-27 13:03 UTC, Andries-Smit commented on tests/helpers/structureMatcher.ts
> +}
missing newline

2017-01-27 13:03 UTC, Andries-Smit commented on tests/mocks/Mendix.ts
> +export const mockMendix = mxMockObject;
missing newline

2017-01-27 13:03 UTC, Andries-Smit commented on tslint.json
> +}
missing newline

2017-01-27 13:03 UTC, Andries-Smit commented on webpack.config.js
> +        postLoaders: [ {
postloader should be conditional in the kara config

2017-01-30 06:45 UTC, edwinmp commented on Gruntfile.js
> +    grunt.registerTask("default", [ "clean build", "watch" ]);
Done.

2017-01-30 06:47 UTC, edwinmp commented on README.md
> +* Render different bar types that is; default, striped and animated
Done.

2017-01-30 06:47 UTC, edwinmp commented on README.md
> +* Show different bar colors that is; success, info, warning, danger
Done.

2017-01-30 06:48 UTC, edwinmp commented on README.md
> +
Removed.

2017-01-30 06:48 UTC, edwinmp commented on karma.conf.js
> +};
Added.

2017-01-30 06:54 UTC, edwinmp commented on package.json
> +  "description": "Progress bar used to show percentage of progress for values 0 to 100",
Removed.

2017-01-30 06:55 UTC, edwinmp commented on package.json
> +    "url": ""
Added.

2017-01-30 06:55 UTC, edwinmp commented on package.json
> +    "url": ""
Added.

2017-01-30 07:42 UTC, edwinmp commented on package.json
> +  "devDependencies": {
Done.

2017-01-30 07:46 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +                        "red-progressbar-text": maximumValue < 1,
Done.

2017-01-30 07:51 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +                        ? maximumValue < 1 ? "Invalid" : `${this.calculatePercentage(progress, maximumValue)}%`
Fixed.

2017-01-30 08:04 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +            this.state.alertMessage ? createElement(Alert, { message: this.state.alertMessage }) : null
Not without having to deal with type errors given the recent strictness. They don't like components returning null. Frankly, I find it better & cleaner this way :)

2017-01-30 10:17 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +            window.console.warn("The maximum value is less than one. Progress is set to Invalid");
Removed.

2017-01-30 10:36 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +            bootstrapStyle = contextObject.get(bootstrapStyleAttribute || "") as BootstrapStyle || bootstrapStyle;
If bootstrapStypeAttribute is not set, it passes in "" which lets the function return undefined/null.
It's a shortcut & more accurate way of writing
```
bootstrapStyle = boostrapStypeAttribute
    ? contextObject.get(bootstrapAttribute) as BootstrapStyle
    : bootstrapStyle
```

2017-01-30 10:37 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +            maximumValue = maximumValueAttribute ? Number(contextObject.get(maximumValueAttribute)) : maximumValue;
Done.

2017-01-30 10:37 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +            [ this.progressAttribute, this.bootstrapStyleAttribute, this.maximumValueAttribute ].forEach((attribute) =>
:)

2017-01-30 10:38 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +dojoDeclare("com.mendix.widget.ProgressBar.ProgressBar", [ WidgetBase ], function (Source: any) {
Removed

2017-01-30 10:39 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ProgressBar.xml
> +                <attributeType name="Integer" />
Done.

2017-01-30 10:39 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ProgressBar.xml
> +                <attributeType name="Integer" />
Done.

2017-01-30 10:40 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ProgressBar.xml
> +                <enumerationValue key="default">Default (None)</enumerationValue>
Done.

2017-01-30 10:40 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/Alert.ts
> +
Added.

2017-01-30 13:23 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/__tests__/ProgressBar.spec.ts
> +        expect(wrapper.childAt(0).text()).toEqual(`${300}%`);
Done.

2017-01-30 13:23 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/__tests__/ProgressBar.spec.ts
> +    it("should not have the class widget-progressbar-text-contrast when progress exceeds the threshold", () => {
Done.

2017-01-30 13:23 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ui/ProgressBar.css
> +.widget-progressbar-text-contrast.red-progressbar-text .progress-bar {
Changed to `widget-progressbar-alert`

2017-01-30 13:24 UTC, edwinmp commented on tests/helpers/structureMatcher.ts
> +}
Added.

2017-01-30 13:24 UTC, edwinmp commented on tests/mocks/Mendix.ts
> +export const mockMendix = mxMockObject;
Added.

2017-01-30 13:24 UTC, edwinmp commented on tslint.json
> +}
Added.

2017-01-30 13:24 UTC, edwinmp commented on webpack.config.js
> +        postLoaders: [ {
Moved.

2017-01-30 13:46 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/ProgressBar.ts
> +    private executeMicroflow (action: string | undefined, guid: string | undefined) {
Added page support.

2017-02-02 15:35 UTC, Andries-Smit requested changes
Last review.

2017-02-02 15:35 UTC, Andries-Smit commented on karma.conf.js
> +        console.log("With instrumenter");
Remove the `console.log`

2017-02-02 15:35 UTC, Andries-Smit commented on karma.conf.js
> +};
Not really

2017-02-02 15:35 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +            bootstrapStyle = contextObject.get(bootstrapStyleAttribute || "") as BootstrapStyle || bootstrapStyle;
Don`t agree, its about `contextObject.get("")` that might cause issue later in live. You should get an error via the mx API as the attribute "" does not exist on the context object.

2017-02-02 15:35 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/ProgressBar.xml
> +                <attributeType name="Integer" />
Did you updated the Mendix Demo project too?

2017-02-02 15:35 UTC, Andries-Smit commented on src/com/mendix/widget/ProgressBar/components/Alert.ts
> +        : null as any;
Remove `as any` update typing to
"@types/react": "^15.0.6",
"@types/react-dom": "^0.14.22",

2017-02-03 08:32 UTC, edwinmp commented on karma.conf.js
> +};
Sneaky bugger... added this time... I think. :)

2017-02-03 08:34 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/ProgressBar.ts
> +            bootstrapStyle = contextObject.get(bootstrapStyleAttribute || "") as BootstrapStyle || bootstrapStyle;
Reverted.

2017-02-03 08:35 UTC, edwinmp commented on karma.conf.js
> +        console.log("With instrumenter");
Done.

2017-02-03 09:58 UTC, edwinmp commented on src/com/mendix/widget/ProgressBar/components/Alert.ts
> +        : null as any;
Done.

2017-04-06 06:31 UTC, closed without merging