Feature/react16
FlockOfBirds/progress-bar pull request #4
Opened 2017-07-26 06:36 UTC by McDoyen

* Add react 16 support

2017-07-26 13:30 UTC, acellam requested changes

2017-07-26 13:30 UTC, mistaguy commented on src/ProgressBar.webmodeler.ts
> +            return createElement("div", {},
pass null for prop

2017-07-26 13:30 UTC, mistaguy commented on src/components/Alert.ts
>  export const Alert: StatelessComponent<{ message?: string }> = (props) =>
Make alert generic so that it can be used for different kind of alert like success, info, etc.

2017-07-26 13:30 UTC, mistaguy commented on src/components/Alert.ts
>          : null as any;
remove `as any`

2017-07-28 11:35 UTC, McDoyen commented on src/components/Alert.ts
>          : null as any;
Done

2017-07-28 11:35 UTC, McDoyen commented on src/components/Alert.ts
>  export const Alert: StatelessComponent<{ message?: string }> = (props) =>
Done

2017-08-02 08:27 UTC, merged